Step4
codesquad-members-2022/java-ladder pull request #161
Opened 2022-02-18 00:14 UTC by nathan29849

안녕하세요 nathan입니다.
사다리 구현 4 단계에 대한 풀 리퀘스트를 보냅니다. (항상 감사합니다!)

---
### 이름 처리 (5글자 이상일 시 ".." 처리)
![image](https://user-images.githubusercontent.com/67811880/154534161-11795981-23a9-460a-9960-7be603d8d0be.png)

### Test 결과(domain)
#### LineTest
![image](https://user-images.githubusercontent.com/67811880/154534384-b4d581e2-a96c-4dd2-818a-ae172a197fdf.png)

#### StringTest
![image](https://user-images.githubusercontent.com/67811880/154534431-716848b2-a08c-4ba5-8e86-0039feff5ac8.png)

---

- 테스트 코드를 작성하는 것이 아직은 익숙치 않아 '일단 해보자'라는 마음으로 작성했습니다.

2022-02-19 15:21 UTC, tmdgusya requested changes
안녕하세요. 리뷰어 로치입니다 :)

전반적으로 변수명 / 메소드명에 대한 고민이 필요해 보입니다.
초반에는 이런 이름짓기를 하는것 또한 부담이 되고 어려울 수 있다고 생각해요.
다만 어떤 변수명이 좀더 남이 봤을때 이해하기 좋은지를 고민해보시고 코드를 작성하는 습관을 들이시는게 좋지 않을까? 라는 생각을 해봅니다.

Test 도 잘 작성해주시고. 미션도 잘 따라오시는거 같네요 👍 
리뷰에 언급하신 부분들을 한번 고민해보시고, 다시 수정해서 올려주시면 감사하겠습니다 :)

2022-02-19 15:21 UTC, tmdgusya commented on src/Main.java
> +        results = Arrays.asList(Input.getResult().split(","));
"," 와 같은 구분자는 상수로 추출이 가능할까요?

2022-02-19 15:21 UTC, tmdgusya commented on src/domain/Line.java
> +    private ArrayList<Boolean> points = new ArrayList<>();
final 로 쓰시는게 좋을거 같네요.
final 에 대해서 한번 학습해 보시는게 좋을거같네요.

2022-02-19 15:21 UTC, tmdgusya commented on src/domain/Line.java
> +    public Boolean get(int index) {
일급 콜렉션 처럼 사용하시고 계시군요 👍 
만약 모르고 계셨다면 아래 내용을 한번 학습해보시고 정리해보시면 좋을거 같아요
https://jojoldu.tistory.com/412

2022-02-19 15:21 UTC, tmdgusya commented on test/domain/LineTest.java
> +    @DisplayName("Line이 제대로 생성이 되는가(원소들이 Boolean 값으로 잘 들어갔는가)")
테스트에 DisplayName 을 지으실때 `~일때 ~ 이다` 라는 when... then 구조로 짜면 좋지 않을까? 라는 생각을 해봅니다.
보는 사람 입장에서는 어떤 상황에서 어떤 결과값이 도출되어야 이 테스트가 성공하는지 알기 힘들수도 있다는 생각이 드네요.

2022-02-19 15:21 UTC, tmdgusya commented on src/domain/Ladder.java
>      public String Info() {
메소드 명에 대한 고민이 필요해보입니다.
Info 라는 메소드는 어떤 행위를 하는 걸까요? 
다른 사람이 이 코드를 본다면 한번에 이해할 수 있을까요? 한번 고민해보시면 좋을거 같네요.

2022-02-19 15:21 UTC, tmdgusya commented on src/domain/Ladder.java
>          this.numberOfPeople = players.size();
numberOfPeople 은 꼭 필요할까요?

2022-02-19 15:21 UTC, tmdgusya commented on src/Main.java
> +        results = Arrays.asList(Input.getResult().split(","));
애초에 Input 의 getPlayer() 에서 split 을 해서 오는건 어떨까요? 한번 생각해 보시면 좋을듯하네요.

2022-02-19 15:21 UTC, tmdgusya commented on src/domain/Ladder.java
> +    public Ladder(List<String> players, List<String> results, int m) {
`m` 이란 변수명에 대해선 생각이 많이 필요해 보입니다.
개인적으로 `클린코드` 에 대한 고민은 남 혹은 같이 일하는 팀원들과 얼마나 좋은 코드를 작성하는가에 따라 달려있다고 보는데요.
남이 봤을때 이해할 수 있는 변수명을 고민해보시는게 좋을거 같습니다.

2022-02-19 15:50 UTC, merged

2022-02-20 14:01 UTC, nathan29849 commented on src/Main.java
> +        results = Arrays.asList(Input.getResult().split(","));
그 부분에 대해 고려를 못했던 것 같습니다. getPlayer()에서 받아오는 것으로 수정하고, ","같은 구분자는 앞으로 상수를 쓰도록 해보겠습니다!

2022-02-20 15:14 UTC, nathan29849 commented on src/domain/Line.java
> +    private ArrayList<Boolean> points = new ArrayList<>();
감사합니다!

2022-02-20 15:14 UTC, nathan29849 commented on src/domain/Line.java
> +    public Boolean get(int index) {
일급 콜렉션을 모르고 사용했는데, 학습해보겠습니다!

2022-02-20 15:49 UTC, nathan29849 commented on test/domain/LineTest.java
> +    @DisplayName("Line이 제대로 생성이 되는가(원소들이 Boolean 값으로 잘 들어갔는가)")
보는 사람 입장에서 생각하지 않고 테스트 코드를 작성했던 것 같습니다 ㅠㅠ 다음부터는 리뷰해주신 부분을 중점적으로 생각할 수 있도록 하겠습니다

2022-02-20 15:53 UTC, nathan29849 commented on src/domain/Ladder.java
>          this.numberOfPeople = players.size();
생각해보니 굳이 변수로 선언하여 쓸 필요가 없었던 것 같습니다! 해당  부분 수정하겠습니다

2022-02-20 15:54 UTC, nathan29849 commented on src/domain/Ladder.java
> +    public Ladder(List<String> players, List<String> results, int m) {
정말 제 기준에서만 생각했던, 이기적인 변수명이었던 것 같습니다.. 다음 부터는 변수명에 대해 충분히 숙고하고 코드를 작성하겠습니다.

2022-02-20 15:59 UTC, nathan29849 commented on src/domain/Ladder.java
>      public String Info() {
이 부분도 생각없이 작성했습니다.. 앞으로는 더욱 주의해서 변수명을 작성할 수 있도록 하겠습니다.

2022-02-20 16:02 UTC, nathan29849 commented
남겨주신 리뷰를 모두 확인하고 반영하여 수정하였습니다. 
시간들여 리뷰해주셔서 정말 고개숙여 감사의 말씀드립니다!
말씀해주신 일급 콜렉션은 학습 후 따로 정리하는 시간을 갖도록 하겠습니다.

2022-02-21 13:45 UTC, tmdgusya commented
@nathan29849 
넵 변수명은 코딩을 하는 과정 중 점점 발전해 나가는 것이죠 :)
너무 자책하지마시길 바랍니다 ㅎㅎ 저도 처음에는 변수명 이상하게 많이 적었어요 
앞으로 좋게 적으면 되니까 상심하지 마시고 즐겁게 코딩하시길 바랍니다! 화이팅~!

2022-02-21 13:47 UTC, nathan29849 commented
감사합니다!!