[포키] 4단계 - 리팩토링2 제출
codesquad-members-2022/java-ladder pull request #163
Opened 2022-02-18 03:00 UTC by Seokho-Ham

안녕하세요 호눅스 😃 

<궁금한 점>
1. 3단계 리뷰에서 InputUtil에서 입력을 String으로 받는 부분을 String배열로 바꿔서 받는 방식으로 바꾸는건 어떻겠냐고 리뷰를 해주셨습니다. 
전 입력을 받은 뒤, 받은 입력값을 가공하는건 컨트롤러의 역할이라고 생각이 되서 저렇게 구현했었는데 InputView 내에서 값을 가공해서 넘겨줘도 되는걸까요?? (현재는 리뷰해주신대로 구현했습니다)

2. 4단계의 `Line 객체에서 선을 그릴 수 있는지 여부를 판단하는 로직에 대한 단위 테스트를 반드시 추가한다.` 라는 부분이 있습니다.
현재 제 코드에서는 저 로직이 private 접근제어자로 작성이 되어 있는데 테스트를 위해서 public으로 바꾸는건 이상한것 같아서 일단은 Line 생성 후 연속된 스텝을 가진 결과가 나오는지만 테스트를 했습니다. (제대로 된 테스트가 되지 못하겠다는 알지만..ㅎ)
이런 경우는 어떻게 테스트를 하는게 좋을까요?

항상 리뷰 감사합니다. 덕분에 놓쳤던 부분들, 몰랐던 부분들을 알아가고 있습니다 🙇🏻‍♂️

2022-02-19 10:03 UTC, wheejuni requested changes
수고 많으셨습니다~ 👍 
피드백 참고 부탁드려요!

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/controller/GameController.java
> +        String[] users = InputUtil.getUserNameInput();;
배열을 선택하신 이유가 있을까요? 가급적이면 `java.util.Collection` 을 상속받거나 구현한 클래스들을 사용해주세요.

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/controller/GameController.java
> +        OutputUtil.printLadder(ladderGame.getGameResult());
`OutputUtil` 에서 `Util` 은 어떤 의미를 갖는다고 생각하시는지요?
그리고 요구사항을 구현하는 로직이 담긴 클래스를 유틸이라고 부를 수 있을까요? 저는 그렇게 생각하지는 않긴 합니다.
유틸이라는 이름을 가진 클래스라면 프로젝트나 모듈에 관계없이 범용적으로 사용될 수 있어야 한다고 보거든요. 포키의 의견도 궁금하네요.

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/Ladder.java
> +        }
조건문에서 새로운 예외를 던지는 접근 자체가 나쁘진 않지만, 만약 이게 조건문의 전부라면....
`validateLadderHeight` 에서 바로 던져버리는 건 어떨까요? 기왕에 던져야 하는 거라면 빨리 던지고 로직을 단순화시키는 게 좋을 것 같은데요?

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/Ladder.java
> +        return sb.toString();
`toString()` 안에서 `StringBuilder` 를 사용하고, `forEach` 문까지 순회하는 접근을 권하고 싶진 않습니다.
`.toString()` 은 객체를 뷰의 형태로 표현한다는 개념으로 접근해야 할 메소드가 아니라, 디버그 목적으로 정말 이 객체에 대해 재빠르게 파악할 수 있는 문자열을 간단히 생성해 주는 메소드여야 한다고 생각하고요, 늘 가벼워야 한다고 생각합니다.

제 경험인데 `.toString()` 에서 로직을 복잡하게 가져가다가 버그가 생겨서, 그 버그를 식별하고 디버그하는데 정말 한참의 시간을 허비한 기억이 있어요. 
가급적 이 영역은 로직을 가볍게 가져가고, 직접 구현하시는 것보다는 IDE가 자동으로 생성해주는 정도의 로직으로도 충분하다고 생각해요.

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/Line.java
> +    private List<String> row;
질문이 있습니다.

1. `String` 을 선택하신 이유.
2. `row` 가 가진 값에 따라 분기하는 로직을 반드시 구현해야 할 텐데, 그렇다면 그것을 구현하는 기준은 `String.equals()` 가 되나요?

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/Line.java
> +    }
좋은 시도입니다 👍

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/User.java
> +        this.name = addPadding(user);
보니까 `addPadding` 이라는게 사용자가 입력한 이름에 공백을 추가하여, 디스플레이 될 때 편의성을 제공하는 거네요.
그렇다면 이게... `User` 라는 객체가 본질적으로 기억해야 할 사용자의 이름이 _한 칸의 공백이 추가된 이름_ 인걸까요?
디스플레이될 문자열을 내보낼때 추가해주는 방법이 더 좋은 건 아닐까? 생각해봅니다...

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/User.java
> +    private User(String user) {
공개될 필요가 없는 생성자를 적절히 가린 것 좋습니다 👍

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/service/GameService.java
> +        sb.append("\n");
`\n` 이 개행문자가 아닌 OS가 있을 수도 있지 않을까요?
_(이번 프로젝트의 요구사항 범위를 벗어나는 질문을 드린 것이기는 합니다)_

2022-02-19 10:03 UTC, wheejuni commented on src/main/java/domain/service/GameService.java
> +    private List<User> getUserList(String[] users) {
파라메터가 `List<String>` 이었으면 `.map()` 한방에 해결될 텐데... 아쉽다는 생각이 드시지요?
_물론 어레이로도 비슷한 구현이 가능하기는 합니다_

2022-02-20 08:19 UTC, Seokho-Ham commented on src/main/java/controller/GameController.java
> +        String[] users = InputUtil.getUserNameInput();;
3단계 리뷰에서 배열 타입으로 받는건 어떻겠냐고 리뷰를 해주셔서 바꿔보았습니다!
이 부분에서 궁금한 점이 있는데, InputUtil의 메서드 내에서 입력값을 List형태로 만들어서 컨트롤러에게 넘겨줘도 되는건가요?
뷰에서는 입력만 받고 받은 데이터를 변경해서 모델에 전달하는건 컨트롤러의 몫이라고 생각했는데 크게 상관 없는걸까요?

2022-02-20 08:30 UTC, Seokho-Ham commented on src/main/java/domain/Ladder.java
> +        }
생각해보니 예외를 위해서 굳이 조건문을 만드는건 불필요한것 같네요! 감사합니다!

2022-02-20 08:33 UTC, Seokho-Ham commented on src/main/java/controller/GameController.java
> +        OutputUtil.printLadder(ladderGame.getGameResult());
전 그냥 출력과 입력을 돕는 도구라고 생각을 해서 Util을 사용했는데, 지금보니 사다리타기 게임에만 맞춰진 클래스네요.
OutputView로 변경을 해야겠습니다.

2022-02-20 08:40 UTC, Seokho-Ham commented on src/main/java/domain/Ladder.java
> +        return sb.toString();
그동안 계속 toString을 잘못 사용해왔었네요..ㅎㅎ
리뷰 해주신 덕분에 toString 메서드를 어떤 목적으로 사용해야하는지에 대해 생각해볼 수 있었습니다!
(5단계에서 위의 로직은 제거했습니다!)

2022-02-20 08:42 UTC, Seokho-Ham commented on src/main/java/domain/User.java
> +        this.name = addPadding(user);
안그래도 5단계에서는 User에는 정확한 이름만 들고 있고, 출력 시 사용하는 객체에서 addPadding 메서드를 가지고 출력하도록 변경했습니다!

2022-02-20 08:49 UTC, Seokho-Ham commented on src/main/java/domain/service/GameService.java
> +    private List<User> getUserList(String[] users) {
Arrays.asList() 메서드를 사용했어도 됐겠네요..ㅎㅎ
5단계에서는 매개변수를 List로 변경해야겠습니다.

2022-02-20 08:52 UTC, Seokho-Ham commented on src/main/java/domain/Line.java
> +    private List<String> row;
1. 가장 처음 단계에서는 특별히 분기 없이 출력만 하는 조건이었어서 String을 선택했고 이후에는 계속 사용해왔습니다.
2. `String.equals()`를 사용해서 분기를 했습니다.

5단계부터는 위에 상수들은 사실상 출력을 위한 부분이라고 생각이 되어서 OutputView로 옮긴 후 List의 데이터 타입을 Integer로 변경했습니다.
-1,0,1 형식으로 데이터를 저장하고 조건에 따라  분기하는데 이것도 별로 안좋은 방법일까요? 이런 경우 Boolean이 가장 좋은 선택지일까요?

2022-02-20 08:55 UTC, Seokho-Ham commented on src/main/java/domain/service/GameService.java
> +        sb.append("\n");
그부분까지는 크게 고려하지 않았습니다ㅠ
`System.lineSeparator()` 를 사용해서 처리하는 방식이 있군요! 리뷰를 보고 찾아보고 알게됐네요ㅎㅎ  감사합니다!

2022-02-20 08:57 UTC, Seokho-Ham commented
리뷰 감사합니다! 5단계에서 피드백 반영해서 제출하겠습니다 :)

2022-02-20 11:39 UTC, wheejuni commented on src/main/java/controller/GameController.java
> +        String[] users = InputUtil.getUserNameInput();;
네 그정도의 가공은 좋다고 생각합니다.

2022-02-20 11:39 UTC, wheejuni commented on src/main/java/domain/Line.java
> +    private List<String> row;
`enum` 을 적극적으로 사용하시는 건 고려해보지 않으셨을까요?

2022-02-20 11:39 UTC, wheejuni commented
5단계 피알을 기대하며 머지합니다.

2022-02-20 11:40 UTC, merged