[BC] 사다리 구현 4 단계 - 리팩토링 2
codesquad-members-2022/java-ladder pull request #166
Opened 2022-02-18 03:44 UTC by honeySleepr

안녕하세요~~ 오늘도 깃 branch의 숲을 뚫고 왔습니다 🌲 

4단계 PR 요청드립니다
* 이름에 padding을 추가하여 길이 6을 맞추는 addPadding() 추가
 ![image](https://user-images.githubusercontent.com/92678400/154613301-0955218b-6faf-48ee-a228-6be5969e4241.png) 
![image](https://user-images.githubusercontent.com/92678400/154613366-7468d4d3-b44d-430f-ba37-fc13088ac9ad.png)

* Line 클래스를 만들어 사다리맵을 ArrayList<Line> 에 들고 다니도록 수정
* 테스트 코드 추가

---

#### 질문 있습니다!

오직 테스트 코드를 위해 메소드 접근제어자를 private -> default 로 바꾸게 되었는데, 이럴 경우 애초에 설계가 잘못된걸까요, 아니면 이렇게 해도 괜찮은가요..?

2022-02-19 04:49 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
코멘트 참고 부탁드려요~

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/LadderGame.java
> +        Controller Controller = new Controller(input, output);
`Input`, `Output` 분리시도 좋습니다 👍 
그런데 그러면 컨트롤러의 역할은 어떤 것인지 조금 궁금해지기는 합니다. 

밑에서 이어서 볼게요.

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Controller.java
>      private final Output output;
이 두 가지를 주입받아서 어떤 효과를 기대하셨는지 궁금합니다!

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    private final int HEIGHT;
인스턴스 변수의 네이밍 규칙에 맞지 않는군요. 

```suggestion
    private final int width;
    private final int height;

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    void make() {
`package-private` 접근수준을 의도하셨나요?

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    protected List<Line> getLadderList() {
Getter 인데 `protected` 갖게 된 이유 궁금합니다!

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Line.java
> +    Line(int width) {
여기도 오픈 수준이 애매한데요.

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Line.java
> +    Line(int width) {
`width` 라는 생성자 파라메터를 받고 있긴 합니다만, 이 값이 객체에 직접 할당되는 것이 아닌,
for loop를 돌면서 라인을 하나씩 추가하는 형태를 갖고 있습니다(사다리 게임의 원리를 생각해보면 당연한 일 같군요).
그렇다면 이건 `Line` 의 생성자가 수행해야 할 기능이 아닌 `LineGenerator` 와 같은 외부 종속성을 통해 수행되어야 할 로직으로 보입니다.
어떻게 생각하시는지 궁금하네요.

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Line.java
> +    static final String BLANK_SPACE = "     ";
`public` 제어자를 주는게 좋을 거 같기는 합니다.

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Line.java
> +    static final Random random = new Random();
`Random` 을 스태틱하게 선언해놓고 쓰는 것의 단점에는 어떤 게 있으려나요?
(힌트: 테스트)

2022-02-19 04:49 UTC, wheejuni commented on Java_Class/LadderGame/src/test/study/StringBuilderTest.java
> +public class StringBuilderTest {
학습 목적의 테스트 좋습니다. 👍 
앞으로도 이런 방식으로 새로운 API, 새로운 라이브러리를 학습해 주세요~

2022-02-19 08:24 UTC, honeySleepr reviewed
안녕하세요! 상세한 리뷰 너무 감사드립니다🙇‍♂️🙇‍♂️🙇‍♂️
달아주신 리뷰들에 댓글을 달았는데 PR, 코드리뷰 기능이 아직 익숙지 않아서 이렇게 다는게 맞는건지 모르겠습니다.. 뭔가 잘못되었다면.. 미리 사과드립니다;;

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    private final int HEIGHT;
아핫 감사합니다! 
상수로 쓰인다고 생각해서 저렇게 지었는데, 
이 경우에는 처음부터 값이 지정된 상수가 아니라 나중에 값이 할당되는 "변수"이기 때문에 일반 변수처럼 네이밍 해주면 된다고 이해하면 될까요??

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    void make() {
네 맞습니다
항상 public, private 만 써와서 이번에는 접근 가능 범위를 최대한 좁히려고 default 접근제어자를 시도해본 것인데, 이런 형태로는 일반적으로 안쓰이나요..?

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/Controller.java
>      private final Output output;
제가 아직 의존성 주입이란게 있다! 정도까지만 알고 있어서
main에서는 객체를 만들어 주입 해주고, 객체를 사용해서 실행하는 로직은 Controller에서는 구현해보자는 생각으로
이렇게 코드를 짜보았습니다.

말씀해주신대로 Controller 역할이 딱히 없어서, Controller를 없애고 해당 코드들을 main 메소드로 옮기는게 나을까요?

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    protected List<Line> getLadderList() {
여기도 `getLadderList()`가 같은 패키지에 있는`Controller` 클래스에서만 호출되기 때문에 접근 범위를 줄여도 되지 않을까 생각하였습니다. (protected는 실수이고, default로 두려고 했던 것 같습니다.)
getter는 public이 국룰인지 궁금합니다!🤩

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/Line.java
> +    static final String BLANK_SPACE = "     ";
넵!

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/Line.java
> +    static final Random random = new Random();
모든 테스트가 같은 Random 객체를 공유하게 되어 테스트들이 독립적으로 수행되지 않는 문제가 생기는 걸까요..?

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/Line.java
> +    Line(int width) {
여기도 `Line` 객체를 생성하는 클래스는 같은 패키지의 `LadderMaker` 뿐이여서 생성자의 접근 범위를 같은 패키지내로 줄여도 되지 않을까 생각하였습니다

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/Line.java
> +    Line(int width) {
`Line` 클래스는 사다리의 한 행을 나타내는데  필요한 `List<String>` 만을 필드로 가지게 하고, 그 행을 실제로 만드는 행위를 하는 클래스는 `LineGenerator`로 따로 만들어서 역할을 분리하는게 좋을 것 같다는 뜻으로 이해했는데, 제가 잘 이해한게 맞나요..?🥺

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/domain/Line.java
> +    Line(int width) {
사다리를 담는 컬렉션인 `List<Line>` 에 Line을 만드는 로직 까지 들어가는 것은 불필요한 것 같아서 wheejuni님 제안해주신 방법이 더 합리적인 것 같습니다

이 경우 Line 클래스에는 필드로 `Line<String>` 하나만을 두게 되면, 이게 말로만 듣던 "일급 컬렉션"이 되는 것인가요?🤩

2022-02-19 08:24 UTC, honeySleepr commented on Java_Class/LadderGame/src/test/study/StringBuilderTest.java
> +public class StringBuilderTest {
넵!🥳

2022-02-20 11:10 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Controller.java
>      private final Output output;
학습 목적으로 이해하겠습니다! 좋은 시도에요 👍

2022-02-20 11:11 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    private final int HEIGHT;
상수로 쓰인다면 `private final` 이면 안될 것 같은데요? 그리고 말씀하신 것처럼 객체가 생성될때마다 새로운 값이 할당되는, 명확하게 **변수** 입니다.

2022-02-20 11:11 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    void make() {
일반적으로 쓰이냐, 안쓰이냐보단 목적에 맞게 사용하셨는지를 보고 싶었어요.

2022-02-20 11:12 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/LadderMaker.java
> +    protected List<Line> getLadderList() {
네 사실 게터는 특정한 규칙에 명시되어 있는 기준이긴 한데요
https://stackoverflow.com/questions/3295496/what-is-a-javabean-exactly

`protected` 수준으로 노출해야 하는 게터라면 게터 자체가 꼭 필요한지도 다시 고민해보시면 좋을 것 같기는 합니다.

2022-02-20 11:13 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Line.java
> +    Line(int width) {
`LadderMaker` 의 패키지 위치가 변경되면요? 
`LadderMaker` 에 `Line` 의 구현이 종속되네요? 만약 외부 요소에서의 접근이 필요하다면, 그 요소가 접근할 생성자를 하나 `public` 으로 열어두고 제공하는게 맞지 않을까 싶긴 합니다.

2022-02-20 11:14 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Line.java
> +    Line(int width) {
완전한 형태의 일급 컬렉션은 아닐 것 같습니다

2022-02-20 11:14 UTC, wheejuni commented on Java_Class/LadderGame/src/domain/Line.java
> +    static final Random random = new Random();
아뇨 오히려 거꾸로입니다. 모든 객체가 각자 만든 `Random` 을 사용해서 테스트 가능성이 거의 0에 수렴하게 되었죠
(테스트 목적의 `Random` 객체 주입 불가능)

이건 지금 이런 얘기도 있다 라고 대충 듣고 넘어가주세요~

2022-02-20 11:15 UTC, wheejuni commented
수고 많으셨습니다. 지금 단계에선 이것으로 충분하다고 생각해서 머지할게요~

2022-02-20 11:15 UTC, merged