[후] 사다리 구현 4단계 - 리팩토링 2
codesquad-members-2022/java-ladder pull request #169
Opened 2022-02-18 09:24 UTC by who-hoo

호눅스 아프지 마세요... 😢 💊

---

사다리 구현 4단계로 요구사항에 맞게 리팩토링을 진행하였습니다.
- 각각의 역할에 맞도록 패키지를 분리하고 적절하게 변경
- 플레이어 이름 제약(최대 5글자) 제거하고, 글자수 제한 없이 이름을 가질 수 있되 출력할 때 5글자를 초과할 시 말줄임표(..)를 붙이도록 수정
- 필수 단위 테스트 추가
  - Line 객체에서 선을 그릴 수 있는지 여부를 판단하는 로직
    - 선을 제대로 그렸다면 중복없이 Ladder가 생성될 것이므로 생성된 Ladder에 겹치는 선("|-----|-----|")을 포함하지 않는지 확인
  - 사다리 결과를 출력할 때 최대 5글자를 정확히 출력하는지 처리하는 로직
    - PlayerList가 출력을 위한 문자열을 반환하는 부분(toString())에서 부족한 글자에는 패딩을, 초과하는 글자에는 말줄임표(..)를 붙여 각 플레이어 이름을 5글자씩 처리하고 있는지 확인  

### 고민되는 점
- 테스트 하려는 로직이 정상적으로 수행됬다면 무언가의 결과가 이럴거야~ 라는 흐름으로 테스트 하려는 로직(메서드) 그 자체가 아닌 무언가의 결과로 로직에 대한 단위테스트를 해도 될까요? 요구사항에 있는 `~하는 로직에 대한 단위테스트`를 필수로 하라는게 그 로직을 수행하는 메서드 자체의 테스트를 작성하는 것인지 요구사항이 긴가민가 합니다..ㅎㅎ

2022-02-18 14:27 UTC, tmdgusya commented
안녕하세요 리뷰어 로치입니다 :) 

몇가지 코드를 보았는데 변수명과 함수명에 대한 생각을 한번 가져보면 어떨까 싶어서 리뷰해드립니다.

```java

    public int positiveInteger(String input) throws IllegalArgumentException {
        try {
            int n = Integer.parseInt(input);
            validateNumber(n);
            return n;
        } catch (NumberFormatException e) {
            throw subdivideNumberFormatException(input);
        }
    }
```

일단 InputValidator 안에 있는 메소드 중 하나인데요.
메소드 명이 isPositive() 혹은 validateXXX 식으로 가는게 더 좋지 않을까란 생각을 해봅니다.
method 명은 기본적으로 동사형태를 쓰시는게 표현하기에 좋습니다.

```java
PositiveIntegerValidator.validate(Interger input) 
```
처럼 떼어내는 것 또한 방법일 수 있겠죠?
코드를 표현하는데는 여러가지 방법들이 있으니 다른 라이브러리 혹은 좋은 코드들에서 Validator 를 어떻게 구현했는지 공부해보시는것도 추천드립니다.

말이 조금 길어졌는데 아래와 같이 메소드명이 동사가 아닐 경우 이 메소드 명만으로는 어떤일을 하는 메소드인지 추론하기 힘들다고 생각됩니다.
```java
    public String[] names(String input) throws IllegalArgumentException {
        String[] names = input.replaceAll(" ", "").split(",");
        if (names.length < LadderGame.MIN_PLAYER) {
            throw new IllegalArgumentException("이름을 쉼표로 구분하여 " + LadderGame.MIN_PLAYER + "명 이상 입력해주세요.");
        }
        return names;
    }
```

아마도 `이름표를 쉼표로 구분해서 최소 인원만큼은 입력해 달라는 것`일텐데
위의 조건을 메소드 이름으로 풀어내시는걸 추천해드립니다.
메소드 명만 보고도 이 함수가 어떤 일을 하는지 알 수 있게끔요.

좋은 코드는 좋은 변수명, 좋은 메소드 명에서 부터 시작합니다. 
앞으로 많은 이름 짓기에 좀 더 많은 고민을 하시면서 어떻게 해야 잘 표현할 수 있을지 고민해보시는걸 추천드려요.

2022-02-18 14:51 UTC, tmdgusya requested changes
개인적으로 테스트 코드도 많고 study(학습) 테스트를 남기신 부분이 인상적이였습니다.
좋은 코드를 작성하기 위한 방법으로 테스트 코드를 작성하는 습관또한 좋은 것이라고 생각하기에, 열심히 테스트를 작성하신 부분에서 일단 따봉드립니다 👍

패키지 또한 미션에 맞게 잘 분배하신거 같네요.
package-private 를 이용해 접근제어자에 대한 관심을 가지신것에 대단히 놀랐습니다.
외부로 어떤 파일이 공개되야 하는지에 대한 고민을 하신것 같더라고요.
이참에 접근제어자를 어떻게 사용하는 것이 좋은지 정리해보시면 좋을거 같아요.

다만 계속해서 걸리는 점은 메소드 명 혹은 변수 명이 해당 변수나 메소드가 표현하고자 하는 바를 잘 표현하지 못하고 있다고 생각됩니다.  이름 짓기가 너무 어렵다면 JavaLibrary 와 같은 다른 코드들을 살펴보면서 어떻게 표현하고 있는지 살펴보시는 것도 추천드립니다. 남의 코드를 보면서 또 배우는 점이 많거든요.

미션 4단계 진행하느라 고생많으셨습니다 :)
전반적으로 코드가 깔끔해서 좋은 코드를 작성하기 위해 고민해봐야할것들을 드린거 같네요.
리뷰 받으신 부분 한번 수정해서 다시 올려주시면 될거 같습니다~!

2022-02-18 14:51 UTC, tmdgusya commented on src/main/java/domain/ladder/LadderRow.java
> +    LadderRow(int width) {
혹시 public 을 없애신 이유가 무엇일까요?

2022-02-18 14:51 UTC, tmdgusya commented on src/main/java/domain/player/Player.java
> +    Player(String name) throws IllegalStateException {
고의적으로 없앴다고 생각하는데 혹시 package-private 을 사용하신걸까요?
다른 패키지에서는 import 할수 없게끔?

2022-02-18 14:51 UTC, tmdgusya commented on src/main/java/util/InputValidator.java
>      public String[] names(String input) throws IllegalArgumentException {
메소드명을 고려해주세요~!
메소드 명만 보고도 어떤 행위를 하는것인지 알 수 있어야 합니다.
names 라는 메소드 명은 메소드 명을 추론하기가 너무 힘드네요.

2022-02-18 14:51 UTC, tmdgusya commented on src/test/java/domain/player/PlayerListTest.java
> +    }
한번쯤 테스트 명에 대해서도 생각해보시는게 좋은데요.
위 처럼 `말줄임표와 함께 최대 5글자를 리턴하는지 테스트 ` 가 나은지 `플레이어 명을 출력할때 다섯 글자로 출력된다` 가 조금 더 명확한지 생각해보셔도 좋을거 같아요. 저는 보통 `뭐일때 뭐뭐한다.` 라고 많이 적는 편이에요.

개인적인 생각일수도 있어서 한번 이런것도 고민해보시면 좋을듯 합니다 :)

2022-02-18 14:51 UTC, tmdgusya commented on src/test/java/domain/player/PlayerTest.java
> +    @DisplayName("이름을 입력하지 않으면 플레이어 생성 실패")
DisplayName 안의 설명이 표현력이 좋아 메소드명만 보고도 어떤 테스트를 하는지 알수 있겠군요. 👍

2022-02-19 15:41 UTC, honux77 commented on src/test/java/domain/player/PlayerListTest.java
> +    }
저는 뭐일때 뭐뭐해야한다라고 쓰는 편입니다 ㅎㅎ.

2022-02-19 15:42 UTC, honux77 commented
미션이 짧아서 이건 제가 머지할게요. 감사합니다. 로치

2022-02-19 15:42 UTC, merged

2022-02-19 19:32 UTC, who-hoo commented on src/main/java/domain/ladder/LadderRow.java
> +    LadderRow(int width) {
`LadderRow`는 `Ladder`만 알고 있으면(가지고 있으면) 되고, 다른 클래스들은 `Ladder`외의 정보 - `Ladder`가 어떻게 구성되어 있는지(`LadderRow`나 `LadderElement`)는 알 필요가 없다고 판단하였기 때문입니다. 그래서 ladder 패키지에서는 `Ladder`를 제외하고는 pakage-private를 사용하여 사다리의 구성 요소(?)를 감추어 보았습니다.

2022-02-19 19:33 UTC, who-hoo commented on src/main/java/domain/player/Player.java
> +    Player(String name) throws IllegalStateException {
넵! 현재 구현 단계에서는 플레이어 목록(PlayerList)만 한 번 출력하면 되기 때문에 각 Player에 대해서는 몰라도 될거라고 생각했습니다.

---

제가 패키지 분리와 public, private 외의 접근 제어자를 처음 사용해보는데 우선은 공개 범위를 최대한 적게 가져가는 것이 좋을 거라고 생각했어요. 
- 후에 감춰둔 클래스가 공개될 필요가 생기더라도 넓은 공개 범위로의 변경은 비교적 간단하지만(보다 견고한 프로그램을 위해 클라이언트와 잘못된 상호작용에 대비하여 검증을 더 철저히 하거나 테스트를 추가하는 등의 추가 작업은 필요할 수 있지만 단순히 접근 제어자를 변경하는데 따라오는 사이드 이펙트는 없음)
- 넓은 범위에서 좁은 범위로의 변경은 어렵기 때문에(빨간줄 작렬) 그렇게 생각했습니다.

2022-02-19 20:02 UTC, who-hoo commented
@tmdgusya 세심한 리뷰 너무 감사드립니다ㅎㅎ

단순히 답을 알려주시는게 아니라 스스로 생각해 볼 수 있게끔 고민거리(질문)을 던져주셔서 스스로 찾아보면서 공부도 하고 너무 좋았어요!
믿기지 않으시겠지만 변수와 메서드명 정말 많이 고민하고 신경썼던건데...🙊  갈 길이 아직 멀구나 느꼈습니다ㅋㅋ 더 고민하고 더 노력해보겠습니다! 많이 하다보면 나아지겠죠 중간중간에 칭찬도 해주셔서 기분 좋게 자극과 동기부여가 되었습니다. 다시 한 번 감사드려요😊

제가 개선 사항을 너무 늦게 반영하는 바람에 이미 머지가 되어 버렸는데, 혹시 짚어주신 부분을 개선한 내용을 새로 PR올려서 리뷰 요청드려도 될까요?

2022-02-20 10:30 UTC, tmdgusya commented
@who-hoo 음 시간상 다음미션 주제도 리팩토링인 만큼 해당 미션 진행하시면서 올려주셔도 좋을거 같아요 :)